const cssVarColor = (name) => `rgb(var(${name}) / <alpha-value>)`

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './index.html',
        './src/**/*.{js,ts,jsx,tsx}',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                background: {
                    DEFAULT: cssVarColor('--bg-primary-rgb'),
                },
                surface: {
                    1: cssVarColor('--bg-surface-100-rgb'),
                    2: cssVarColor('--bg-surface-200-rgb'),
                    3: cssVarColor('--bg-surface-300-rgb'),
                    50: cssVarColor('--bg-primary-rgb'),
                    100: cssVarColor('--bg-surface-100-rgb'),
                    200: cssVarColor('--bg-surface-200-rgb'),
                    300: cssVarColor('--bg-surface-300-rgb'),
                    400: '#a1a1aa',
                    500: '#71717a',
                    600: '#52525b',
                    700: '#3f3f46',
                    800: '#27272a',
                    900: '#18181b',
                    950: '#09090b',
                },
                text: {
                    primary: cssVarColor('--text-primary-rgb'),
                    secondary: cssVarColor('--text-secondary-rgb'),
                    muted: cssVarColor('--text-muted-rgb'),
                },
                accent: {
                    300: '#93c5fd',
                    400: '#60a5fa',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                    DEFAULT: cssVarColor('--color-accent-rgb'),
                    soft: cssVarColor('--accent-soft-rgb'),
                },
                status: {
                    violet: cssVarColor('--status-violet-rgb'),
                    green: cssVarColor('--status-green-rgb'),
                    amber: cssVarColor('--status-amber-rgb'),
                    red: cssVarColor('--status-red-rgb'),
                    blue: cssVarColor('--status-blue-rgb'),
                    'violet-soft': 'var(--status-violet-soft)',
                    'green-soft': 'var(--status-green-soft)',
                    'amber-soft': 'var(--status-amber-soft)',
                    'red-soft': 'var(--status-red-soft)',
                    'blue-soft': 'var(--status-blue-soft)',
                },
                primary: {
                    50: '#eff6ff',
                    100: '#dbeafe',
                    200: '#bfdbfe',
                    300: '#93c5fd',
                    400: '#60a5fa',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                    800: '#1e40af',
                    900: '#1e3a8a',
                    950: '#172554',
                },
                success: {
                    50: '#f0fdf4',
                    100: '#dcfce7',
                    200: '#bbf7d0',
                    300: '#86efac',
                    400: '#4ade80',
                    500: '#22c55e',
                    600: '#16a34a',
                    700: '#15803d',
                    800: '#166534',
                    900: '#14532d',
                    950: '#052e16',
                },
                timer: {
                    50: '#fffbeb',
                    100: '#fef3c7',
                    200: '#fde68a',
                    300: '#fcd34d',
                    400: '#fbbf24',
                    500: '#f59e0b',
                    600: '#d97706',
                    700: '#b45309',
                    800: '#92400e',
                    900: '#78350f',
                    950: '#451a03',
                },
                stroke: cssVarColor('--border-subtle-rgb'),
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                mono: ['JetBrains Mono', 'Roboto Mono', 'monospace'],
                display: ['Inter', 'system-ui', 'sans-serif'],
            },
            fontSize: {
                '2xs': ['0.65rem', { lineHeight: '1.3' }],
                'display-lg': ['2rem', { lineHeight: '1.2' }],
                'display-xl': ['2.75rem', { lineHeight: '1.15' }],
                'display-2xl': ['3.5rem', { lineHeight: '1.1' }],
            },
            spacing: {
                '4.5': '1.125rem',
                '13': '3.25rem',
                '15': '3.75rem',
                '18': '4.5rem',
                '22': '5.5rem',
                '26': '6.5rem',
                '30': '7.5rem',
            },
            borderRadius: {
                xl: '0.75rem',
                '2xl': '1rem',
                '3xl': '1.5rem',
                '4xl': '2rem',
                '5xl': '2.5rem',
            },
            animation: {
                'pulse-slow': 'pulse-slow 3s ease-in-out infinite',
                'ping-slow': 'ping 2s cubic-bezier(0, 0, 0.2, 1) infinite',
                'spin-slow': 'spin 3s linear infinite',
                breathe: 'breathe 3s ease-in-out infinite',
                'slide-up': 'slide-up 0.24s cubic-bezier(0.16, 1, 0.3, 1)',
                'slide-down': 'slide-down 0.24s cubic-bezier(0.16, 1, 0.3, 1)',
                'fade-in': 'fade-in 0.2s ease-out',
                'scale-in': 'scale-in 0.2s cubic-bezier(0.16, 1, 0.3, 1)',
                'bounce-in': 'bounce-in 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
                check: 'check 0.3s ease-out forwards',
                confetti: 'confetti 0.8s ease-out forwards',
                'bounce-small': 'bounce-small 0.3s ease-out',
            },
            keyframes: {
                'pulse-slow': {
                    '0%, 100%': { opacity: '1' },
                    '50%': { opacity: '0.72' },
                },
                breathe: {
                    '0%, 100%': { transform: 'scale(1)', opacity: '1' },
                    '50%': { transform: 'scale(1.015)', opacity: '0.95' },
                },
                'slide-up': {
                    '0%': { transform: 'translateY(10px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                'slide-down': {
                    '0%': { transform: 'translateY(-10px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                'fade-in': {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                'scale-in': {
                    '0%': { transform: 'scale(0.96)', opacity: '0' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                'bounce-in': {
                    '0%': { transform: 'scale(0)', opacity: '0' },
                    '50%': { transform: 'scale(1.08)' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                'bounce-small': {
                    '0%, 100%': { transform: 'scale(1)' },
                    '50%': { transform: 'scale(1.08)' },
                },
                check: {
                    '0%': { transform: 'scale(0)' },
                    '50%': { transform: 'scale(1.15)' },
                    '100%': { transform: 'scale(1)' },
                },
                confetti: {
                    '0%': {
                        transform: 'translateY(-10px) rotate(0deg)',
                        opacity: '1',
                    },
                    '100%': {
                        transform: 'translateY(100vh) rotate(720deg)',
                        opacity: '0',
                    },
                },
            },
            boxShadow: {
                card: 'var(--shadow-card)',
                'card-elevated': 'var(--shadow-card-elevated)',
                glass: 'var(--shadow-card)',
            },
            borderColor: {
                subtle: 'var(--border-subtle)',
            },
            transitionTimingFunction: {
                page: 'cubic-bezier(0.4, 0, 0.2, 1)',
            },
        },
    },
    plugins: [],
}
